# Generated by Django 6.0.1 on 2026-01-20 16:24

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='company',
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название компании')),
                ('url', models.URLField(blank=True, null=True, verbose_name='Ссылка на сайт компании')),
                ('state_orders', models.BooleanField(default=True, verbose_name='Статус получения заказов')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец компании')),
            ],
            options={
                'verbose_name': 'Компания розничной торговли',
                'verbose_name_plural': 'Список компаний розничной торговли',
                'ordering': ('-name',),
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastname', models.CharField(blank=True, max_length=100, null=True, verbose_name='Фамилия')),
                ('firstname', models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя')),
                ('middlename', models.CharField(blank=True, max_length=100, null=True, verbose_name='Отчество')),
                ('email', models.EmailField(error_messages={'invalid': 'Invalid email format'}, max_length=254, validators=[django.core.validators.EmailValidator()], verbose_name='email address')),
                ('phone_number', models.CharField(max_length=16, verbose_name='Номер телефона')),
                ('city', models.CharField(blank=True, max_length=50, verbose_name='Город')),
                ('street', models.CharField(blank=True, max_length=100, verbose_name='Улица')),
                ('house', models.CharField(blank=True, max_length=5, verbose_name='Дом')),
                ('structure', models.CharField(blank=True, max_length=5, verbose_name='Корпус')),
                ('building', models.CharField(blank=True, max_length=5, verbose_name='Строение')),
                ('apartment', models.CharField(blank=True, max_length=5, verbose_name='Квартира')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Контакты пользователя',
                'verbose_name_plural': 'Список контактов пользователя',
            },
        ),
    ]
