# Generated by Django 6.0.1 on 2026-01-24 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_user_first_name_user_last_name_user_middle_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='email',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='middlename',
        ),
    ]
