# Generated by Django 6.0.1 on 2026-02-12 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_alter_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_rrc',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=10, verbose_name='Рекомендуемая цена'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена'),
        ),
    ]
