# Generated by Django 6.0.1 on 2026-02-12 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_product_price_rrc_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='article',
            field=models.CharField(max_length=10, unique=True, verbose_name='Артикул'),
        ),
    ]
