# Generated by Django 6.0.1 on 2026-02-13 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_alter_product_article'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='companies',
        ),
    ]
