# Generated by Django 6.0.1 on 2026-02-14 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_remove_category_companies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='property',
            name='value',
            field=models.CharField(blank=True, max_length=30, verbose_name='Единица измерения'),
        ),
    ]
