# Generated by Django 6.0.1 on 2026-02-15 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_alter_property_name_alter_property_value'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'ordering': ('name',), 'verbose_name': 'Характеристика', 'verbose_name_plural': 'Список характеристик'},
        ),
    ]
