# Generated by Django 6.0.1 on 2026-02-15 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_alter_category_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productproperty',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='backend.product', verbose_name='Продукт'),
        ),
        migrations.AlterField(
            model_name='productproperty',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='backend.property', verbose_name='Характеристика'),
        ),
        migrations.AlterField(
            model_name='productproperty',
            name='quantity',
            field=models.CharField(max_length=50, verbose_name='Значение параметра'),
        ),
    ]
