# Generated by Django 6.0.1 on 2026-02-15 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_alter_productproperty_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Общая стоимость заказа'),
        ),
    ]
